import type { CSSProperties } from 'react';

export const S: Record<string, CSSProperties> = {
  authPage: {
    minHeight: '100vh',
    background: 'linear-gradient(160deg, #fffbeb 0%, #fef3c7 45%, #fde68a 100%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1.5rem',
  },
  shell: {
    minHeight: '100vh',
    background: 'linear-gradient(160deg, #fffbeb 0%, #fef3c7 45%, #fde68a 100%)',
    color: '#1f2937',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    background: '#f59e0b',
    color: '#fff',
    padding: '0.85rem 1.5rem',
    boxShadow: '0 4px 16px rgba(245,158,11,0.25)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  main: {
    maxWidth: 1120,
    margin: '0 auto',
    padding: '1.5rem 1rem 4rem',
    width: '100%',
    display: 'grid',
    gap: '1.25rem',
  },
  card: {
    background: '#fff',
    border: '1px solid #fed7aa',
    borderRadius: '1rem',
    padding: '1.25rem',
    boxShadow: '0 8px 30px rgba(120,53,15,0.06)',
  },
  authCard: {
    background: '#fff',
    borderRadius: '1.5rem',
    boxShadow: '0 8px 40px rgba(120,53,15,0.12)',
    padding: '2rem 1.75rem',
    width: '100%',
    maxWidth: 400,
    display: 'grid',
    gap: '1rem',
  },
  inp: {
    width: '100%',
    padding: '0.85rem 1rem',
    borderRadius: '0.85rem',
    border: '1.5px solid #e5e7eb',
    fontSize: '1rem',
    outline: 'none',
    display: 'block',
    boxSizing: 'border-box',
  },
  select: {
    width: '100%',
    padding: '0.85rem 1rem',
    borderRadius: '0.85rem',
    border: '1.5px solid #e5e7eb',
    fontSize: '1rem',
    background: '#fff',
    display: 'block',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    padding: '0.85rem 1rem',
    borderRadius: '0.85rem',
    border: '1.5px solid #e5e7eb',
    fontSize: '1rem',
    minHeight: 96,
    resize: 'vertical',
    boxSizing: 'border-box',
  },
  primaryBtn: {
    width: '100%',
    padding: '0.9rem',
    background: 'linear-gradient(135deg, #f59e0b, #d97706)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.85rem',
    fontSize: '1rem',
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(245,158,11,0.35)',
  },
  outlineBtn: {
    width: '100%',
    padding: '0.85rem',
    background: 'transparent',
    color: '#d97706',
    border: '1.5px solid #f59e0b',
    borderRadius: '0.85rem',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
  dangerBtn: {
    padding: '0.75rem 1rem',
    background: '#fff',
    color: '#dc2626',
    border: '1.5px solid #fca5a5',
    borderRadius: '0.75rem',
    fontSize: '0.95rem',
    fontWeight: 700,
    cursor: 'pointer',
  },
  smallBtn: {
    padding: '0.5rem 0.9rem',
    background: 'linear-gradient(135deg, #f59e0b, #d97706)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.6rem',
    fontSize: '0.85rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
  smallOutlineBtn: {
    padding: '0.5rem 0.9rem',
    background: 'transparent',
    color: '#d97706',
    border: '1.5px solid #f59e0b',
    borderRadius: '0.6rem',
    fontSize: '0.85rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
  headerLogoBtn: {
    background: 'none',
    border: 'none',
    color: '#fff',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: 0,
  },
  headerBtn: {
    padding: '0.45rem 1rem',
    background: 'rgba(255,255,255,0.2)',
    color: '#fff',
    border: '1.5px solid rgba(255,255,255,0.5)',
    borderRadius: '0.65rem',
    fontSize: '0.88rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
  linkBtn: {
    background: 'none',
    border: 'none',
    padding: 0,
    color: '#d97706',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '0.92rem',
    textDecoration: 'underline',
  },
  errorBox: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: '0.65rem',
    padding: '0.65rem 0.9rem',
    color: '#dc2626',
    fontSize: '0.88rem',
  },
  successBox: {
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    borderRadius: '0.65rem',
    padding: '0.65rem 0.9rem',
    color: '#166534',
    fontSize: '0.88rem',
  },
  infoBox: {
    background: '#fff7ed',
    border: '1px solid #fdba74',
    borderRadius: '0.75rem',
    padding: '0.8rem 1rem',
    color: '#9a3412',
    fontSize: '0.92rem',
  },
  label: {
    display: 'block',
    fontWeight: 600,
    fontSize: '0.88rem',
    color: '#78350f',
    marginBottom: '0.3rem',
  },
  fieldGroup: {
    display: 'grid',
    gap: '0.3rem',
  },
};

export const sectionTitle: CSSProperties = {
  margin: 0,
  color: '#78350f',
  fontWeight: 800,
};

export const subheading: CSSProperties = {
  margin: 0,
  color: '#92400e',
  fontWeight: 700,
};

export const mutedText: CSSProperties = {
  margin: 0,
  color: '#6b7280',
};

export const tableCell: CSSProperties = {
  padding: '0.75rem',
  textAlign: 'left',
  borderBottom: '1px solid #fde68a',
};

export const tableHeadCell: CSSProperties = {
  ...tableCell,
  color: '#78350f',
  fontWeight: 700,
  background: '#fef3c7',
  borderBottom: '2px solid #fed7aa',
};

export function statusPill(status: string): CSSProperties {
  const colors: Record<string, { bg: string; fg: string; border: string }> = {
    draft: { bg: '#fff7ed', fg: '#9a3412', border: '#fdba74' },
    ranking: { bg: '#fef3c7', fg: '#92400e', border: '#fbbf24' },
    ranked: { bg: '#e0f2fe', fg: '#0369a1', border: '#7dd3fc' },
    active: { bg: '#dcfce7', fg: '#166534', border: '#86efac' },
    playoffs: { bg: '#ede9fe', fg: '#6d28d9', border: '#c4b5fd' },
    completed: { bg: '#f3f4f6', fg: '#374151', border: '#d1d5db' },
  };
  const token = colors[status] || colors.draft;
  return {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.3rem',
    padding: '0.25rem 0.6rem',
    borderRadius: 999,
    fontSize: '0.78rem',
    fontWeight: 700,
    textTransform: 'capitalize',
    background: token.bg,
    color: token.fg,
    border: `1px solid ${token.border}`,
  };
}
